# Site settings

# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb

title: yechunxi
description: sherry的博客
baseurl: ""
url: "http://yechunxi.github.io"
github_username:  yechunxi
permalink: /:year/:month/:day/:title/

# other links
github_username:  yechunxi
email: yechunxi00@163.com

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
